/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form.dialog.grupa;

import components.TableModelGrupe;
import controller.Communication;
import domain.Grupa;
import domain.Kurs;
import form.PocetnaZaposleni;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofija Nedeljkovic
 */
public class GrupaPretrazi extends javax.swing.JDialog {

    ArrayList<Grupa> grupe;
    /**
     * Creates new form GrupaPretrazi
     */
    public GrupaPretrazi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        tableGrupe.setModel(new TableModelGrupe());
        popuniKombo();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbKurs = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGrupe = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnVrati = new javax.swing.JButton();
        btnDetaljno = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PRETRAZI GRUPE");

        jLabel2.setText("Kursevi:");

        cmbKurs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tableGrupe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableGrupe);

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnVrati.setText("Vrati na sve grupe");
        btnVrati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiActionPerformed(evt);
            }
        });

        btnDetaljno.setText("Vidi detaljno");
        btnDetaljno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljnoActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni grupu");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jButton1.setText("Otkazi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(cmbKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretrazi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnVrati)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDetaljno)
                                .addGap(60, 60, 60)
                                .addComponent(btnIzmeni)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVrati)
                    .addComponent(btnDetaljno)
                    .addComponent(btnIzmeni))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiActionPerformed
        // TODO add your handling code here:
        popuniTabelu();
    }//GEN-LAST:event_btnVratiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        // TODO add your handling code here:
        Kurs kurs = (Kurs) cmbKurs.getSelectedItem();
        ArrayList<Grupa> poKursevima = new ArrayList<>();
        
        for (Grupa grupa : grupe) {
            if(grupa.getKurs().getKursID()==kurs.getKursID()){
            
                poKursevima.add(grupa);
            }
        }
        if(poKursevima.isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe grupe po zadatoj vrednosti.");
            return;
        }
        TableModelGrupe tmg = (TableModelGrupe) tableGrupe.getModel();
        tmg.dodajGrupe(poKursevima);
        JOptionPane.showMessageDialog(this, "Sistem je našao grupe po zadatoj vrednosti.");
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnDetaljnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljnoActionPerformed
        // TODO add your handling code here:
        int selected = tableGrupe.getSelectedRow();
        if(selected >= 0){
        
            TableModelGrupe tmg = (TableModelGrupe) tableGrupe.getModel();
            Grupa gr = tmg.vratiGrupu(selected);
            PocetnaZaposleni pz = (PocetnaZaposleni) getParent();
            JOptionPane.showMessageDialog(this, " Sistem je učitao grupu.");
            new GrupaPrikazi(pz, false, gr).setVisible(true);
        }else{
        
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita grupu. Nije selektovan nijedna grupa.");
        }
    }//GEN-LAST:event_btnDetaljnoActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        // TODO add your handling code here:
        int selected = tableGrupe.getSelectedRow();
        if(selected >= 0){
        
            TableModelGrupe tmg = (TableModelGrupe) tableGrupe.getModel();
            Grupa gr = tmg.vratiGrupu(selected);
            PocetnaZaposleni pz = (PocetnaZaposleni) getParent();
             JOptionPane.showMessageDialog(this, "Sistem je učitao grupu.");
            GrupaKreiraj gk = new GrupaKreiraj(pz, false);
            gk.setVisible(true);
            gk.izmeniGrupu(gr);
        }else{
        
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita grupu. Nije selektovan nijedna grupa."); 
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrupaPretrazi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrupaPretrazi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrupaPretrazi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupaPretrazi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GrupaPretrazi dialog = new GrupaPretrazi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetaljno;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnVrati;
    private javax.swing.JComboBox<Object> cmbKurs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableGrupe;
    // End of variables declaration//GEN-END:variables

    private void popuniKombo() {
        try {
            ArrayList<Kurs> kursevi = Communication.getInstance().getAllKurs();
            cmbKurs.removeAllItems();
            for (Kurs kurs : kursevi) {
                cmbKurs.addItem(kurs);
            }
        } catch (IOException ex) {
            Logger.getLogger(GrupaPretrazi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void popuniTabelu() {
        try {
            grupe = Communication.getInstance().getAllGrupe();
            TableModelGrupe tmg = (TableModelGrupe) tableGrupe.getModel();
            tmg.dodajGrupe(grupe);
        } catch (IOException ex) {
            Logger.getLogger(GrupaPretrazi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
