/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import components.TableModelKurs;
import controller.Communication;
import domain.Clanstvo;
import domain.Kurs;
import domain.Polaznik;
import form.dialog.ocena.SviKursevi;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofija Nedeljkovic
 */
public class PocetnaPolaznik extends javax.swing.JFrame {

    Polaznik p;
    Kurs k;
    /**
     * Creates new form PocetnaPolaznik
     */
    public PocetnaPolaznik(Polaznik p) {
        initComponents();
        setLocationRelativeTo(null);
        this.p = p;
        tableKur.setModel(new TableModelKurs());
        popuniTabelu();
        txtSrednja.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSrednja = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKur = new javax.swing.JTable();
        btnVidiSrednju = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PRETRAZI SVE KURSEVE I OCENE");

        tableKur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableKur);

        btnVidiSrednju.setText("Vidi srednju ocenu");
        btnVidiSrednju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVidiSrednjuActionPerformed(evt);
            }
        });

        jMenu1.setText("Svi kursevi");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Moji kursevi");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Vidi i oceni");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtSrednja, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(btnVidiSrednju))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVidiSrednju)
                    .addComponent(txtSrednja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVidiSrednjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVidiSrednjuActionPerformed
        // TODO add your handling code here:
        int selected = tableKur.getSelectedRow();
        int brojac = 0;
        int ocene = 0;
        double srednja = 0;
        boolean flag = false;
        if(selected >= 0){
        
            try {
                TableModelKurs tmk = (TableModelKurs) tableKur.getModel();
                k = tmk.vratiKurs(selected);
                ArrayList<Clanstvo> clanstva = Communication.getInstance().getAllClanstvo();
                for (Clanstvo clanstvo : clanstva) {
                    if(clanstvo.getGrupa().getKurs().getKursID()==k.getKursID()){
                    
                        if(clanstvo.getOcena()!= 0){
                        
                            flag= true;
                            brojac++;
                            ocene += clanstvo.getOcena();
                        }
                    }
                }
                if(flag){
                
                    srednja = (double)ocene/brojac;
                    txtSrednja.setText(Double.toString(srednja));
                }else{
                
                    JOptionPane.showMessageDialog(this, "Kurs jos nije ocenjen.");
                }
            } catch (IOException ex) {
                Logger.getLogger(PocetnaPolaznik.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
        
            JOptionPane.showMessageDialog(this, "Niste izabrali kurs.");
        }
    }//GEN-LAST:event_btnVidiSrednjuActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sistem je našao kurseve po zadatoj vrednosti.");
        new SviKursevi(this, false, p).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVidiSrednju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKur;
    private javax.swing.JTextField txtSrednja;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        try {
            ArrayList<Kurs> kursevi = Communication.getInstance().getAllKurs();
            TableModelKurs tmk = (TableModelKurs) tableKur.getModel();
            tmk.dodajKurseve(kursevi);
            
            
        } catch (IOException ex) {
            Logger.getLogger(PocetnaPolaznik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
